backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Názov článku", name: "title", widget: "string"}
      - {label: "Dátum", name: "date", widget: "datetime"}
      - {label: "Krátky popis", name: "description", widget: "text"}
      - {label: "Obsah článku", name: "body", widget: "markdown"}
