backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    files:
      - file: "data/blog.json"
        label: "Blogové články"
        name: "blog"
        fields:
          - label: "Zoznam článkov"
            name: "items"
            widget: "list"
            fields:
              - {label: "Názov článku", name: "title_sk", widget: "string"}
              - {label: "Dátum", name: "date", widget: "string"}
              - {label: "Krátky popis", name: "desc_sk", widget: "text"}
              - {label: "Obsah článku", name: "content_sk", widget: "markdown"}
